// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/mannkind/twomqtt"
)

// Injectors from wire.go:

func initialize() *bridge {
	mainConfig := newConfig()
	mainMqttClientConfig := mainConfig.MQTTClientConfig
	mqttProxyConfig := mainMqttClientConfig.MQTTProxyConfig
	mqttProxy := twomqtt.NewMQTTProxy(mqttProxyConfig)
	v := newStateChannel()
	v2 := newCommandChannel()
	mainMqttClient := newMQTTClient(mainMqttClientConfig, mqttProxy, v, v2)
	mainServiceClientConfig := mainConfig.ServiceClientConfig
	mainServiceClient := newServiceClient(mainServiceClientConfig, v, v2)
	mainBridge := newBridge(mainMqttClient, mainServiceClient)
	return mainBridge
}
