// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/mannkind/twomqtt"
)

// Injectors from wire.go:

func initialize() *app {
	mainOpts := newOpts()
	mainSourceOpts := mainOpts.Source
	mainComms := newComms()
	v := mainComms.commandInput
	v2 := mainComms.stateOutput
	mainSource := newSource(mainSourceOpts, v, v2)
	mainSinkOpts := mainOpts.Sink
	mqttOpts := mainSinkOpts.MQTTOpts
	mqtt := twomqtt.NewMQTT(mqttOpts)
	v3 := mainComms.stateInput
	v4 := mainComms.commandOutput
	mainSink := newSink(mqtt, mainSinkOpts, v3, v4)
	mainApp := newApp(mainSource, mainSink)
	return mainApp
}
